title: Types & <br/>Î»-Calculus
remote_theme: pmarsceill/just-the-docs
#color_scheme: foo
compress_html:
  ignore:
    envs: all
  blanklines: true
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
domain: uob-coms30040.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://uob-coms30040.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /     # place folder name if the site is served in a subfolder
plugins:
  - jemoji

nav_external_links:
  - title: Replay
    url: https://www.ole.bris.ac.uk/auth-saml/saml/login?apId=_183_1&redirectUrl=https%3A%2F%2Fwww.ole.bris.ac.uk%2Fwebapps%2Fblackboard%2Fexecute%2Fblti%2FlaunchPlacement%3Fblti_placement_id%3D_3169_1%26course_id%3D_264172_1%26mode%3Dview%26wrapped%3Dtrue%26globalNavigation%3Dfalse
    opens_in_new_tab: true

defaults:
  - scope:
      path: "questions"
    values:
      sheet: true
      question: true
  - scope:
      path: "answers"
    values:
      sheet: true
      answer: true
  - scope:
      path: "papers/*-answers.pdf"
    values:
      exam: true
