defaults:
  - scope:
      path: "questions"
    values:
      sheet: true
      question: true
  - scope:
      path: "answers"
    values:
      sheet: true
      answer: true
  - scope:
      path: "papers/*-answers.pdf"
    values:
      exam: true
